<?php
declare(strict_types=1);

const ROLE_ADMIN = 'Administrator';
const ROLE_PROJECT_OFFICER = 'Project Officer';
const ROLE_SOCIAL_WORKER = 'Social Worker';
const ROLE_APPLICANT = 'Applicant';
const ROLE_BENEFICIARY = 'Beneficiary';

const APPLICATION_STATUS_DRAFT = 'Draft';
const APPLICATION_STATUS_SUBMITTED = 'Submitted';
const APPLICATION_STATUS_UNDER_REVIEW = 'Under Review';
const APPLICATION_STATUS_CHECKED_BY_PDO = 'Checked by PDO';
const APPLICATION_STATUS_REQUIREMENTS_VERIFIED = 'Requirements Verified';
const APPLICATION_STATUS_FOR_ASSESSMENT = 'For Assessment';
const APPLICATION_STATUS_APPROVED = 'Approved';
const APPLICATION_STATUS_APPROVED_FOR_TRAINING = 'Approved for Training';
const APPLICATION_STATUS_REJECTED = 'Rejected';
const APPLICATION_STATUS_FLAGGED = 'Flagged';
const APPLICATION_STATUS_NEEDS_DOCUMENTS = 'Needs Documents';
const APPLICATION_STATUS_NEEDS_CORRECTION = 'Needs Correction';
const APPLICATION_STATUS_TRAINING_ONGOING = 'Training Ongoing';
const APPLICATION_STATUS_COMPLETED = 'Completed';

const APPLICATION_ALLOWED_STATUSES = [
    APPLICATION_STATUS_DRAFT,
    APPLICATION_STATUS_SUBMITTED,
    APPLICATION_STATUS_UNDER_REVIEW,
    APPLICATION_STATUS_CHECKED_BY_PDO,
    APPLICATION_STATUS_REQUIREMENTS_VERIFIED,
    APPLICATION_STATUS_FOR_ASSESSMENT,
    APPLICATION_STATUS_APPROVED,
    APPLICATION_STATUS_APPROVED_FOR_TRAINING,
    APPLICATION_STATUS_REJECTED,
    APPLICATION_STATUS_FLAGGED,
    APPLICATION_STATUS_NEEDS_DOCUMENTS,
    APPLICATION_STATUS_NEEDS_CORRECTION,
    APPLICATION_STATUS_TRAINING_ONGOING,
    APPLICATION_STATUS_COMPLETED,
];

const TRAINING_STATUS_NOT_SCHEDULED = 'Not Scheduled';
const TRAINING_STATUS_SCHEDULED = 'Scheduled';
const TRAINING_STATUS_NOTIFIED = 'Notified';
const TRAINING_STATUS_ATTENDED = 'Attended';
const TRAINING_STATUS_EXCUSED = 'Excused';
const TRAINING_STATUS_MISSED = 'Missed';
const TRAINING_STATUS_COMPLETED = 'Completed';

const TRAINING_SCOPE_ALL = 'all';
const TRAINING_SCOPE_BATCH = 'batch';
const TRAINING_SESSIONS_PER_YEAR = 3;
const TRAINING_BATCH_GROUP_COUNT = 3;
const TRAINING_BATCH_GROUP_SIZE = 100;
const TRAINING_YEARLY_BATCH_CAPACITY = TRAINING_BATCH_GROUP_COUNT * TRAINING_BATCH_GROUP_SIZE;

const TRAINING_ALLOWED_STATUSES = [
    TRAINING_STATUS_NOT_SCHEDULED,
    TRAINING_STATUS_SCHEDULED,
    TRAINING_STATUS_NOTIFIED,
    TRAINING_STATUS_ATTENDED,
    TRAINING_STATUS_EXCUSED,
    TRAINING_STATUS_MISSED,
    TRAINING_STATUS_COMPLETED,
];

const POST_APPROVAL_STATUS_LOCKED = 'Locked';
const POST_APPROVAL_STATUS_UNLOCKED = 'Unlocked';
const POST_APPROVAL_STATUS_IN_PROGRESS = 'In Progress';
const POST_APPROVAL_STATUS_SUBMITTED = 'Submitted';
const POST_APPROVAL_STATUS_VERIFIED = 'Verified';
const POST_APPROVAL_STATUS_REJECTED = 'Rejected';
const POST_APPROVAL_STATUS_NEEDS_CORRECTION = 'Needs Correction';

const POST_APPROVAL_ALLOWED_STATUSES = [
    POST_APPROVAL_STATUS_LOCKED,
    POST_APPROVAL_STATUS_UNLOCKED,
    POST_APPROVAL_STATUS_IN_PROGRESS,
    POST_APPROVAL_STATUS_SUBMITTED,
    POST_APPROVAL_STATUS_VERIFIED,
    POST_APPROVAL_STATUS_REJECTED,
    POST_APPROVAL_STATUS_NEEDS_CORRECTION,
];

const POST_APPROVAL_TASK_AVAILMENT_FORM = 'availment_form';
const POST_APPROVAL_TASK_VALIDATION_FORM = 'validation_form';
const POST_APPROVAL_TASK_MUNGKAHING_PROYEKTO = 'mungkahing_proyekto';
const POST_APPROVAL_TASK_BUSINESS_PLAN = 'business_plan';
const POST_APPROVAL_TASK_BUHAT_SA_PAGPANUMPA = 'buhat_sa_pagpanumpa';
const POST_APPROVAL_TASK_SEMINAR_ATTENDANCE = 'seminar_attendance';
const POST_APPROVAL_TASK_FUND_RELEASE_EVIDENCE = 'fund_release_evidence';

const POST_APPROVAL_INTERACTIVE_TASKS = [
    POST_APPROVAL_TASK_AVAILMENT_FORM,
    POST_APPROVAL_TASK_VALIDATION_FORM,
    POST_APPROVAL_TASK_FUND_RELEASE_EVIDENCE,
];

const TRAINING_SEMINAR_FORM_LABELS = [
    POST_APPROVAL_TASK_AVAILMENT_FORM => 'Availment Form',
    POST_APPROVAL_TASK_VALIDATION_FORM => 'Validation Form',
    POST_APPROVAL_TASK_MUNGKAHING_PROYEKTO => 'Mungkahing Proyekto',
    POST_APPROVAL_TASK_BUSINESS_PLAN => 'Business Plan',
    POST_APPROVAL_TASK_BUHAT_SA_PAGPANUMPA => 'Buhat sa Pagpanumpa',
];

const TRAINING_SEMINAR_FORM_CODES = [
    POST_APPROVAL_TASK_AVAILMENT_FORM,
    POST_APPROVAL_TASK_VALIDATION_FORM,
    POST_APPROVAL_TASK_MUNGKAHING_PROYEKTO,
    POST_APPROVAL_TASK_BUSINESS_PLAN,
    POST_APPROVAL_TASK_BUHAT_SA_PAGPANUMPA,
];
