ALTER TABLE applicant_profiles
    ADD COLUMN IF NOT EXISTS birthdate DATE NULL AFTER address_line,
    ADD COLUMN IF NOT EXISTS age TINYINT UNSIGNED NULL AFTER birthdate,
    ADD COLUMN IF NOT EXISTS gender VARCHAR(40) NULL AFTER age,
    ADD COLUMN IF NOT EXISTS is_4ps TINYINT(1) NOT NULL DEFAULT 0 AFTER gender,
    ADD COLUMN IF NOT EXISTS household_size SMALLINT UNSIGNED NULL AFTER is_4ps,
    ADD COLUMN IF NOT EXISTS sector VARCHAR(120) NULL AFTER household_size,
    ADD COLUMN IF NOT EXISTS livelihood_type VARCHAR(160) NULL AFTER sector,
    ADD COLUMN IF NOT EXISTS completion_submitted_at DATETIME NULL AFTER profile_status;
