CREATE TABLE IF NOT EXISTS application_assessments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    application_id BIGINT UNSIGNED NOT NULL,
    assessor_user_id BIGINT UNSIGNED NOT NULL,
    assessor_staff_profile_id BIGINT UNSIGNED NULL,
    identity_residency_status VARCHAR(40) NOT NULL,
    document_validity_status VARCHAR(40) NOT NULL,
    livelihood_confirmation_status VARCHAR(40) NOT NULL,
    program_fit_status VARCHAR(40) NOT NULL,
    readiness_commitment_status VARCHAR(40) NOT NULL,
    recommendation VARCHAR(40) NOT NULL,
    remarks TEXT NOT NULL,
    direct_worker_user_id BIGINT UNSIGNED NULL,
    direct_worker_name VARCHAR(160) NULL,
    certifying_officer_user_id BIGINT UNSIGNED NULL,
    certifying_officer_name VARCHAR(160) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_application_assessments_application FOREIGN KEY (application_id) REFERENCES applications(id),
    CONSTRAINT fk_application_assessments_assessor_user FOREIGN KEY (assessor_user_id) REFERENCES users(id),
    CONSTRAINT fk_application_assessments_assessor_staff FOREIGN KEY (assessor_staff_profile_id) REFERENCES staff_profiles(id),
    CONSTRAINT fk_application_assessments_direct_worker FOREIGN KEY (direct_worker_user_id) REFERENCES users(id),
    CONSTRAINT fk_application_assessments_certifying_officer FOREIGN KEY (certifying_officer_user_id) REFERENCES users(id)
);
