CREATE TABLE IF NOT EXISTS stage_one_registrations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reference_code VARCHAR(40) NOT NULL UNIQUE,
    first_name VARCHAR(80) NOT NULL,
    middle_name VARCHAR(80) NULL,
    last_name VARCHAR(80) NOT NULL,
    full_name VARCHAR(180) NOT NULL,
    email VARCHAR(160) NOT NULL,
    contact_number VARCHAR(40) NOT NULL,
    complete_address TEXT NOT NULL,
    business_photo_path VARCHAR(255) NOT NULL,
    business_photo_original_name VARCHAR(255) NOT NULL,
    business_photo_mime_type VARCHAR(120) NULL,
    business_photo_file_size BIGINT UNSIGNED NULL,
    valid_id_path VARCHAR(255) NOT NULL,
    valid_id_original_name VARCHAR(255) NOT NULL,
    valid_id_mime_type VARCHAR(120) NULL,
    valid_id_file_size BIGINT UNSIGNED NULL,
    validation_status VARCHAR(40) NOT NULL DEFAULT 'pending',
    validated_by_user_id BIGINT UNSIGNED NULL,
    validated_at DATETIME NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_stage_one_registrations_reviewer FOREIGN KEY (validated_by_user_id) REFERENCES users(id),
    INDEX idx_stage_one_registrations_status (validation_status),
    INDEX idx_stage_one_registrations_email (email),
    INDEX idx_stage_one_registrations_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
